-- MySQL Script generated by MySQL Workbench
-- Sun May  7 13:17:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema results
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `results` ;

-- -----------------------------------------------------
-- Schema results
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `results` DEFAULT CHARACTER SET utf8 ;
USE `results` ;

-- -----------------------------------------------------
-- Table `results`.`Athletes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results`.`Athletes` ;

CREATE TABLE IF NOT EXISTS `results`.`Athletes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `county` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `results`.`Competitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results`.`Competitions` ;

CREATE TABLE IF NOT EXISTS `results`.`Competitions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `event_date` DATETIME NOT NULL,
  `event_place` VARCHAR(45) NOT NULL,
  `Athletes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Competitions_Athletes_idx` (`Athletes_id` ASC) ,
  CONSTRAINT `fk_Competitions_Athletes`
    FOREIGN KEY (`Athletes_id`)
    REFERENCES `results`.`Athletes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `results`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results`.`Results` ;

CREATE TABLE IF NOT EXISTS `results`.`Results` (
  `id` INT NOT NULL,
  `time` TIME NOT NULL,
  `place` INT NOT NULL,
  `Athletes_id` INT NOT NULL,
  `Competitions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Results_Athletes1_idx` (`Athletes_id` ASC) ,
  INDEX `fk_Results_Competitions1_idx` (`Competitions_id` ASC) ,
  CONSTRAINT `fk_Results_Athletes1`
    FOREIGN KEY (`Athletes_id`)
    REFERENCES `results`.`Athletes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_Competitions1`
    FOREIGN KEY (`Competitions_id`)
    REFERENCES `results`.`Competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `results`.`Winners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `results`.`Winners` ;

CREATE TABLE IF NOT EXISTS `results`.`Winners` (
  `id` INT NOT NULL,
  `Competitions_id` INT NOT NULL,
  `Results_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Winners_Competitions1_idx` (`Competitions_id` ASC) ,
  INDEX `fk_Winners_Results1_idx` (`Results_id` ASC) ,
  CONSTRAINT `fk_Winners_Competitions1`
    FOREIGN KEY (`Competitions_id`)
    REFERENCES `results`.`Competitions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Winners_Results1`
    FOREIGN KEY (`Results_id`)
    REFERENCES `results`.`Results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
